### ISSUE TITLE
issue when run

### ISSUE THREAD

**Issue by husssm** [EyadNasr/akwam-dl#1]
File "Akwam_v1.2.py", line 129
SyntaxError: Non-ASCII character '\xd8' in file Akwam_v1.2.py on line 129, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

can solve this ?

**Comment by husssm** [comment]
It’s ok with windows. How to get all episodes link for one series? It’s
possible?
I see only question and press y to download and have : connection
error…retrying

**Comment by EyadNasr** [comment]
![image](https://user-images.githubusercontent.com/62260537/137309185-4ad2b7e1-34c4-447c-a8b1-c9e9d92d1fa1.png)
it works just fine with me... maybe there is something wrong with your connection, I will try and make a Google Colab notebook
