### ISSUE TITLE
akwam-dl_forColab.ipynb failing to search input links

### ISSUE THREAD

**Issue by TheTinyPlunger** [EyadNasr/akwam-dl#4]
[](url)Error when searching links containing the arabic language. Input link: https://akw.to/series/4122/العربجي

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-8-0af169b826dc>](https://localhost:8080/#) in <cell line: 208>()
    224             print("\nPress [q] to end questions, [y] to download or [n] to skip:")
    225             websub1 = '[https://](https://github.com/EyadNasr/akwam-dl/issues/new)' + parent[8:].split('/')[0]
--> 226             links = getlistOfSeasons(parent, '"(' + websub1 + '/series/.+?)"', fff, episodesFlag)
    227         elif parent.find('search') != -1:
    228             fff = True

[<ipython-input-8-0af169b826dc>](https://localhost:8080/#) in getlistOfSeasons(parent, findit, fff, episodesFlag)
    137         else:
    138             uniq = findall(findit, x)
--> 139             extracted_websub = findall('([https://.*?akwam.+?)/[](https://.%2A/?akwam.+?)/[)^ \t\n\r\f\v]+', uniq[0])[0]
    140             uniq = unique(uniq).tolist()
    141             unsrt = [int(i.split('/')[-2]) for i in uniq]

IndexError: list index out of range

![Capture](https://user-images.githubusercontent.com/98702333/228841502-77389308-b6db-4f99-9fa7-d5bf87fd37a7.PNG)
[

**Comment by EyadNasr** [comment]
Okay I fixed it
The reason was not the Arabic letters. Akwam website is changing the domain name of the website, it was 'akwam.cc' and now it is 'eg2.ak4eg.mom'. They are changing it because Egypt keeps blocking them.
![image](https://user-images.githubusercontent.com/62260537/229215222-bc93364d-0308-44e2-a3d4-01123ed55cbc.png)

**Comment by TheTinyPlunger** [comment]
Can confirm it is working now. Thank you for the quick fix Eyad!
